[package]
name = "discord-shuttle-01"
version = "0.1.2"
edition = "2021"

[dependencies]
poise = "0.5.7"
reqwest = { version = "0.11.23", features = ["blocking"] }
serde_json = "1.0.108"
shuttle-poise = "0.35.2"
shuttle-runtime = "0.35.2"
shuttle-secrets = "0.35.0"
tokio = "1.35.1"
